// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yozrnudhjvfabgzqgniw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvenJudWRoanZmYWJnenFnbml3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3NjQ3MjAsImV4cCI6MjA1MDM0MDcyMH0._WO7NT7hH3xUd-wKvN2NaCPXmUaicIdSsRxigayJkM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);